---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:../sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1

cds:
  security.mock.users:
    - name: admin
      password: admin
